version: '2.0'
services:
  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 80:80
  megstarr:
    build:
      context: ./megstarr
    image: megstarr:latest
    ports:
    - "3000:3000"
  techofmany:
    build:
      context: ./techofmany
    image: techofmany:latest
    ports:
    - "3001:3001"
  ratemygm:
    build:
      context: ./ratemygm
    image: ratemygm:latest
    ports:
    - "3002:3002"
